### ISSUE TITLE
Possibly incompatible with movies

### ISSUE THREAD

**Issue by xXxBobDolexXx** [Godzil/Crunchy#11]
Using command "crunchy -u email@gmail.com -p password -f srt -o D:\anime http://www.crunchyroll.com/fullmetal-alchemist-the-conqueror-of-shamballa" does not work.

What happens is that it gives the message saying "You have a premium account! Good!" and then immediately goes to a new line where you can enter commands again

**Comment by Godzil** [comment]
Yes there is an issue with show which are not made of episodes. 
I'm looking at that but the tests I've done have broke thing in an unexpected way so I'm not going to push these changes for now...

**Comment by xXxBobDolexXx** [comment]
No rush or anything, just wondering if there was an update on this issue once the authentication thing gets taken care of

**Comment by Godzil** [comment]
Thanks, I've done some changes at some point to test, but it created issues downloading valid episodes.
I think I need to finish #4 so we could ask directly to download a movie from the complete URL.

**Comment by Godzil** [comment]
I'm going to push some changes that may help with movies. The usage is slightly different and can also be used to download a single episode, but may also be used for download specific episode with direct URL.

So the change is require to put a @ in front of the URL to tell Crunchy it is an episode URL and not a series one. I may change that latter, but it was the simplest way to test this function.
It should works on either command line and using the txt file

Example:

crunchy @http://crunchy/anime/anime-season-3-eps-202-this-is-a-title-688945 -o output

Will download the specific episode given by the URL.

**Comment by xXxBobDolexXx** [comment]
Sounds good, looking forward to trying :)

**Comment by xXxBobDolexXx** [comment]
Just tested the new update, working fine over here!

**Comment by Godzil** [comment]
I finish some tests here and will publish a more official version than the one from yesterday, not a lot of changed, just a log saying that we try to download from the @URL.

The main change is that it will now do a backup of the .crpersistent file before running because I've got an issue while stopping it where this file became empty, and, that's annoying :D 

Also it will now display a warning when scrapping a serie and now episodes founds
The reason for no episodes founds could be:
- The episode names use an unsupported scheme (like momokuri that have episode 1-2, episode 3-4 etc.., this new version should support it now)
- This is a movie and the scrapper can't find season/episode numbers so it find nothing
- There is no episodes available (yet) like placeholder for a new series, or you are in a region where you can't have access to this serie.

And as I said momokuri episode naming scheme should be supported now, I will update here when the test is finished and the new verison published!
