### ISSUE TITLE
Change episode numbering pattern

### ISSUE THREAD

**Issue by Gorklax** [Godzil/Crunchy#25]
This is a super minor complaint, but the only issue I've been running into is how the program numbers the episodes. When it moves to a new season, the season number changes, but the episode number continues in series. For example it will go from S01E12 to S02E13 rather than S02E01. This becomes problematic for media apps like plex as it is not able to correctly identify the episode.

**Comment by JySzE** [comment]
Look up filebot portable it can batch rename them. Portable version is free so make sure to find that one, i always use it after downloading with crunchy and plex detects it perfect after. Make sure you disable local assets in the server library settings so it doesnt use local metadata.

**Comment by JySzE** [comment]
plex loves to ignore file names and only looks at meta data if local assets is left on.

**Comment by Godzil** [comment]
Unfortunately the season/episode number are the value retrieved from CR, it is not computed by Crunchy, I have plan for that but it is a non urgent change as there are possibility to use external tools to renumber.

It is CR that need to received this issue unfortunately, their numbering scheme is not consistent with tool like tvdb, or maybe tvdb provide incorrect data, which is also possible.

From what I understand, CR try to use the anime official numbering scheme for the Anime where tvdb use a pseudo standardised system.

**Comment by skthanu** [comment]
@Godzil I have a problem with this series: it has 3 episode have the same name, and crunchy can not download the second part always like this: 
![Uploading image.png…]
It will not automatically change the name but always show fetching video ... and did nothing.
This is the link for it: http://www.crunchyroll.com/the-ancient-magus-bride
it has 2: s01e01,
2: s02e02,
2: s03e03
Can you please help?

**Comment by UnattendedFlight** [comment]
@skthanu Please edit your comment and blur out or crop out your username and password. People might abuse this information.

To your problem, I recently downloaded Ancient Magus' Bride without problems, it added a "-1" suffix to any episode similar to existing on the drive.

I'm not really qualified to tell you how to fix this problem, but a workaround would be to move already downloaded files to a subfolder before the new set of episodes will download. It wont re-download them unless you remove them from the .crpersistent file..

**Comment by skthanu** [comment]
@UnattendedFlight thank you, that is exactly the problem.
Do you know how to save file as .mp4?

**Comment by skthanu** [comment]
@UnattendedFlight can you please recheck for me with this show : `http://www.crunchyroll.com/jojos-bizarre-adventure`
I can just download until s01e26 while it has about 77 ep (but the name is duplicated), I never download this before.
And also this one: `http://www.crunchyroll.com/boruto-naruto-next-generations`
I've deleted all boruto on the .crpersistent but it can not download.
![image](https://user-images.githubusercontent.com/33084800/32979189-23490dc0-cc83-11e7-9a3f-8a1b92aee523.png)

**Comment by skthanu** [comment]
And also this one, i can not download, this is the error
![image](https://user-images.githubusercontent.com/33084800/32979259-679dac32-cc84-11e7-82ea-7fe3795c7ef1.png)
this is the link: `http://www.crunchyroll.com/children-of-ether`

**Comment by Godzil** [comment]
Children of Ether as it is currently on CR is NOT a serie but just an anime. Crunchy, because of how CR is made right now don't detect movies/ONA you have to use a direct link to download the movie:

Use the form 

@http://www.url/to/movie

So go to the page with the movie, copy the link from it and add an "@" in front when pasting to the command line

**Comment by Godzil** [comment]
For the fact that some show are using the same season number, please complain to CR, Crunchy does not invent the number, they are retreived from CR. (see #51)

**Comment by UnattendedFlight** [comment]
@skthanu A simple google search would do you good. It seems Godzil has no intention of adding custom output formats, so if you wish to convert the files, you should use ffmpeg. E.g: 

`ffmpeg -i "The Ancient Magus_ Bride - s01e02 - [CrunchyRoll].mkv" -codec copy "The Ancient Magus_ Bride - s01e02 - [CrunchyRoll].mp4"`

You could also download any bulk video converter softwares. There are quite a few out there.

Just for the fun of it, do you have the newest version of cruncy? If not, you should update it, and try again. Otherwise, just go with my previous tip and move the downloaded files to a subfolder, for example a folder for each season. Your directory tree would look like this:

> --> E:\COMIC\0001
> -- |--> JoJo's Bizarre Adventure
> -- |-- |--> 01-26 Episodes.
> -- |--> JoJo's Bizarre Adventure Re-Edited
> -- |-- |--> 01-03 Episodes
> -- |--> JoJo's Bizarre Adventure: Stardust Crusaders
> -- |-- |--> 01-24 Episodes
> -- |--> JoJo's Bizarre Adventure: Stardust Crusaders - Battle in Egypt
> -- |-- |--> 25-48 Episodes
> -- |--> JoJo's Bizarre Adventure: Diamond is Unbreakable
> -- |-- |--> 01-39 Episodes

**Comment by skthanu** [comment]
@Godzil thank you, it works when I put '@' before the movie link.

**Comment by skthanu** [comment]
@UnattendedFlight can you please tell me how can i setup so that crunchy can run follow this structure
`--> E:\COMIC\0001
-- |--> JoJo's Bizarre Adventure
-- |-- |--> 01-26 Episodes.
-- |--> JoJo's Bizarre Adventure Re-Edited
-- |-- |--> 01-03 Episodes
-- |--> JoJo's Bizarre Adventure: Stardust Crusaders
-- |-- |--> 01-24 Episodes
-- |--> JoJo's Bizarre Adventure: Stardust Crusaders - Battle in Egypt
-- |-- |--> 25-48 Episodes
-- |--> JoJo's Bizarre Adventure: Diamond is Unbreakable
-- |-- |--> 01-39 Episodes`
or i have to do it manually when it stop working?
this problem also happen with this link `http://www.crunchyroll.com/naruto-shippuden`

**Comment by skthanu** [comment]
@Godzil Hi there, can you please check, do i have any problem with this syntax or something because Crunchy doesn't download this movie always show fetching video.... as below
![image](https://user-images.githubusercontent.com/33084800/33006891-bc71e9d2-cdfe-11e7-8145-f7a897a0b42b.png)
This is the link: `http://www.crunchyroll.com/the-ancient-magus-bride/episode-7-talk-of-the-devil-and-he-is-sure-to-appear-749411`

**Comment by UnattendedFlight** [comment]
@skthanu Crunchy will not follow that structure, crunchy is only a tool to download. (yet in a convenient way. Props to Godzil for continuing to maintain it!) You have to setup whatever folder structure as you go yourself. 

As to the "faulty syntax", it seems to be correct. So as long as it's downloading, what's the problem?

**Comment by skthanu** [comment]
@unattendedFight The problem is if I setup a structure folder like that, I am afraid that cruchy will redownload the same EP, I mean it will download from 1-17 again and stop, it will not download the ep which haven’t been downloaded before. Do you get my point? Sorry for my bad english
About “faulty syntax”: I just can not download this EP and it happens when I download other ep or whole serries, so I think may be that happens becauce of my slow internet connection. So that would be great if this software can show the internet connection speed, i think so.

**Comment by UnattendedFlight** [comment]
@skthanu Try making a backup of the '.crpersistent' and the backup one and deleting them. Try your commands again. The files will be located in your output folder.

**Comment by skthanu** [comment]
@UnattendedFlight I've deleted them, but it still doesn't work.
Still Fetching video for a very long time.
I don't know exactly what is the problem, but i don't think the problem is my internet connection because it all good, may be not because of crunchy because you said you can still download video.
Infact I can just download the .ass file and the video doesn't work.
Please help

**Comment by skthanu** [comment]
@UnattendedFlight  It's Working now, it take 31 mins to download a video 24 mins, maybe because of my internet connection.
![image](https://user-images.githubusercontent.com/33084800/33050738-06b07e92-ce99-11e7-8bfb-87145bc1db48.png)

**Comment by UnattendedFlight** [comment]
@skthanu More likely that your computer was taking a heavy load, causing ffmpeg to work slowly, I've experience that myself, taking 40 minutes for a 24min episode when my server was under heavy traffic/load. Glad it worked out.

**Comment by skthanu** [comment]
@UnattendedFlight Yes, thank you alot for helping me out.

**Comment by Godzil** [comment]
There as been recent changes that should solve most of the seen issues there.
Please open a new issue if any of theses still appear.
