### ISSUE TITLE
Just a quick question

### ISSUE THREAD

**Issue by xXxBobDolexXx** [Godzil/Crunchy#84]
For the new login features that were added, I don't specifically need help finding the values, I just want to make sure I am not going to break anything by doing this

Is the file I need to edit in this folder?

%appdata%\npm\node_modules\crunchy\dist

If it's the one I think it is I'll be set. You don't need to confirm if it'll cause issues, just wanted to ask before experimenting with it.

**Comment by Godzil** [comment]
You just need to edit the config file in the current folder, no need to edit and of Crunchy files!

That’s would not be super user friendly!

**Comment by xXxBobDolexXx** [comment]
Ah thanks, I hadn't checked the readme, just skimmed "crunchy -h"

**Comment by Godzil** [comment]
Well to answer, the "legal" part is more of a "fear' than anything else. They send a takedown notice to the Kodi CR plugin with the only thing they could attack them by claiming that some data used to use the API was copyrighted (which will probably not work in front of a court of law but well)

I want to keep Crunchy as clean as possible by making sure it does not have any direct data that CR could say "you don't have the right to use that". Crunchy is in the gray area, I stil don't enforce the use of a premium account (where I may at some point, because that us premium who make CR to work, I use this tool for multiple reason, I prefer to watch them offline, and especially because  the web version of Crunchy still use flash, a plugin I never used and keep updated just because of them :/)

Anyway
