### ISSUE TITLE
ERROR: {"errorType":1} Cannot get episodes

### ISSUE THREAD

**Issue by d4rkd0s** [Godzil/Crunchy#85]
**Describe the bug**
Sometimes when running `crunchy` it works and sometimes it doesn't

**Expected behavior**
Each time you run `crunchy` it works as expected or provides a clear reason as to what went wrong.

**Screenshots**
```
 * INFO : Crunchy version 1.4.2
 * INFO : Seems we are not currently logged. Let's login!
 * WARN : Retrying to fetch episodes list from5 / 5
 * INFO : Seems we are not currently logged. Let's login!
 * WARN : Retrying to fetch episodes list from4 / 5
 * INFO : Seems we are not currently logged. Let's login!
 * WARN : Retrying to fetch episodes list from3 / 5
 * INFO : Seems we are not currently logged. Let's login!
 * WARN : Retrying to fetch episodes list from2 / 5
 * INFO : Seems we are not currently logged. Let's login!
 * WARN : Retrying to fetch episodes list from1 / 5
 * INFO : Seems we are not currently logged. Let's login!
 * ERROR: {"errorType":1}
 * ERROR: Cannot get episodes from "https://www.crunchyroll.com/blend-s/", please rerun later
Done!
```

**Please fill theses informations:**
(Add a X between brackets to make them ticked if relevant)
 - OS: Mac OS Mojave 10.14 Beta 4 (18A353d)
 - [Y] I'm using the latest version of Crunchy
 - [Y] I have a premium account on CR
 - [N] I am using a VPN
 - My region in the world (country or continent): USA
 - Series you get a problem with (and specify which episode if it is specific to one): Blend-S, but any series results in the same odd functionality.
 - The command line you are running Crunchy with: iTerm2 running `bash`
 - The message Crunchy is giving you, if any:
```
* ERROR: {"errorType":1}
 * ERROR: Cannot get episodes from "https://www.crunchyroll.com/blend-s/", please rerun later
```

**Additional context**
When I ran it the first time I got episode 0 of season 0, and it was the full first episode, I stopped it, to look and it worked. Then when running it again it failed with the following:

```
 * INFO : Crunchy version 1.4.2
 * INFO : Seems we are not currently logged. Let's login!
 * ERROR: Authentication failed:
Done!
```

Then running it again (each time I'm just pressing up arrow and running the previous command) I get the error:

```
* ERROR: {"errorType":1}
 * ERROR: Cannot get episodes from "https://www.crunchyroll.com/blend-s/", please rerun later
Done!
```

After all of that, I'd love to help improve / fix / develop. So I'm going to take a look at some other issues and see if I can apply some work to help out! Maybe even figure out what's going on here with me issue.

Thank you! @Godzil I came to your fork of crunchyroll.js because I saw you active on its issues page. I think you have a great fork and I'd love to help out.

**Comment by d4rkd0s** [comment]
@Godzil So I've been testing over and over. It appears that there's two issues (i think)

- Crunchy sometimes fails to authenticate to CR, maybe theres a better way we can write auth to handle attempts, retries, etc
- Crunchyroll API seems to rate limit auth requests? or all requests in general. I think this is why I reported the above issue, as sometimes I auth and I can't get episodes, and if I wait (10-15 minutes) then retry everything works as intended.

**Comment by Godzil** [comment]
Unfortunately I can really give support if you use the API way of login, because I don’t know what settings you put, and I don’t want any of them to appear here.

Authentification has always been the biggest issue in Crunchy, that’s why I’ve added two “unsupported” way in the code that I can’t document how to set to prevent potential problems with them.

If you haven’t changed anything to the config file, then you are hitting the bug we had some time ago.

If you are using the default method of login, the issue Is probably linked with cloudflare, but it is really hard to know what is happening.

Once you are logged, makes sure you use the same output folder (as the cookies are store there) and the same config file so the next time it will not have to try to log again.

If you want to investigate what is happening, you are more than welcome. My biggest fear here is a bug in the library which is used to scrape data from a cloudflare enabled website.

**Comment by Godzil** [comment]
And yeah there are a lot of poorly implemented thing in Crunchy, this is because of a lot of different reasons, like using node was probably a poor decision choice for such a tool, and the original code is made in a way which make changes (like the retry process I’ve made) to be painful to implement.

**Comment by d4rkd0s** [comment]
Understandable. :smiley_cat:  I would consider building something in a new language. Would you be interested in working on anything new? What languages like Go, Ruby, Python? Or something else? @Godzil

**Comment by d4rkd0s** [comment]
Closing this issue for now, since its a won't fix / can't fix.
